### ISSUE TITLE
remove <cr> 

### ISSUE THREAD

**Issue by ArbitRandomUser** [Klafyvel/vim-slime-cells#10]
in lines 6 through 9 in plugin/slime_cells.vim

```noremap <unique> <script> <silent> <Plug>SlimeCellsSend :<c-u>call slime_cells#send_cell()<cr>
noremap <unique> <script> <silent> <Plug>SlimeCellsNext :<c-u>call slime_cells#go_to_next_cell()<cr>
noremap <unique> <script> <silent> <Plug>SlimeCellsPrev :<c-u>call slime_cells#go_to_previous_cell()<cr>
noremap <unique> <script> <silent> <Plug>SlimeCellsSendAndGoToNext :<c-u>call slime_cells#send_cell_and_go_to_next()<cr>
noremap <unique> <script> <silent> <Plug>SlimeCellsSendAndGoToNext :<c-u>call slime_cells#send_cell_and_go_to_next()<cr>

```

the additional \<cr\> causes the cursor to go to a new line after the text is sent ,

this destorys the purpose of slime_preserve_curpos in vim-slime

**Comment by Klafyvel** [comment]
Hi,
I am not sure I understand your issue. If I remove these `<cr>` the commands won't be executed anymore, will they?

**Comment by ArbitRandomUser** [comment]
oh alright, i am mistaken 
i had an extra \<CR\> in my vim init for the keybinding

sorry for the noise.

**Comment by Klafyvel** [comment]
No problem, have fun using vim-slime-cells. :)
