### ISSUE TITLE
Color issue again.

### ISSUE THREAD

**Issue by khoroshyy** [Klafyvel/vim-slime-cells#3]
Hi

I am trying the last version of slime  and cell slime and getting color issue as descrivef in https://github.com/Klafyvel/vim-slime-cells/issues/1

Error detected while processing /home/petro/.vim/bundle/vim-slime-cells/plugin/slime_cells.vim:
line   51:
E254: Cannot allocate color ctermbg=
Press ENTER or type command to continue

The outputs from below commands are:
:echo synIDattr(synIDtrans(hlID(g:slime_cells_highlight_from)), "fg", "GUI")
StateBlue
:echo synIDattr(synIDtrans(hlID(g:slime_cells_highlight_from)), "fg", "cterm")
5
:echo synIDattr(synIDtrans(hlID(g:slime_cells_highlight_from)), "bg", "GUI")
nothing
:echo synIDattr(synIDtrans(hlID(g:slime_cells_highlight_from)), "bg", "cterm")
nothing.
Any Idea what it can be.

**Comment by Klafyvel** [comment]
Hi, thank you for creating this issue !

Can you try the `color-issue-again` branch, please? It might fix the issue.

**Comment by khoroshyy** [comment]
Hm.
Get the same answer.
line   51:
E254: Cannot allocate color ctermbg=
Press ENTER or type command to continue

**Comment by Klafyvel** [comment]
My guess is the GUI bg is not defined, and that messes up the highlight command. I just pushed commit [cb13e4d](https://github.com/Klafyvel/vim-slime-cells/commit/cb13e4d42381336d925b8c758f5cf2f5bd432562) to the `color-issue-again` branch. Can you try it?

**Comment by Klafyvel** [comment]
Hi! any news regarding this issue?

**Comment by khoroshyy** [comment]
Hi.
Sorry I got distracted from it and forgot about it. I will test it tomorrow
and let you know.
Best.
Petro

**Comment by khoroshyy** [comment]
Hi.
I am not sure if I installed the correct release but the mistake is the
same.

**Comment by Klafyvel** [comment]
Ah... Could you post your configuration somewhere, as well as the version of vim you are using?

**Comment by khoroshyy** [comment]
Hi.
here are my tmux.conf and  vim
https://drive.google.com/file/d/1y5Y-WC_ZrqEVRrS3hky-3CV8_PsdDgjw/view?usp=share_link
https://drive.google.com/file/d/1PCqXOd5tw-jd--ea0PqoZu8YLu0VXy7S/view?usp=share_link

My vim version:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 19 2022 04:59:57)
Included patches: 1-2269, 3612, 3625, 3669, 3741
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        +mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-tiO2Sp/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.7 -lm     

Thanks.
Petro.

**Comment by khoroshyy** [comment]
The above commit is working... Thanks.

**Comment by Klafyvel** [comment]
Awesome! I'll merge this in the main branch.
