### ISSUE TITLE
SlimeCellsSendAndGoToNext and Julia multiline comments

### ISSUE THREAD

**Issue by fofusa** [Klafyvel/vim-slime-cells#6]
Currently SlimeCellsSendAndGoToNext does not handle properly julia multiline comments with two or more empty lines

## MWE:

```
##
# Normal cell, should be executed
a = 1
##
# Commented out cell using multiline comments, should not be executed
#=


a = 2
=#
##
# test cell, should return 1, not 2
a
##
```

## Expected output (using 3x SlimeCellsSendAndGoToNext)
```
julia> a
1
```

## Actual output
```
ERROR: syntax: incomplete: unterminated multi-line comment #= ... =#
Stacktrace:
 [1] top-level scope
   @ none:1

julia> a = 2
2

julia> =#
ERROR: syntax: unexpected "="
```

## Note : 
Removing one of the two blank lines in the commented out cell fixes the problem.
Hope it helps improving vim-slime,

FoFuSa

**Comment by Klafyvel** [comment]
Hi! thank you for reporting the issue.

I believe this is not an issue with vim-slime-cells, you can fix the issue by activating bracketed paste within vim-slime:

```vim
let slime_bracketed_paste=1
```

With the above setting you get:

```julia
julia> # Normal cell, should be executed
       a = 1
1

julia> # Commented out cell using multiline comments, should not be executed
       #=


       a = 2
       =#

julia> # test cell, should return 1, not 2
       a
1

julia>
```
