### ISSUE TITLE
Correct delimiter regex for quarto

### ISSUE THREAD

**Issue by thesimonho** [Klafyvel/vim-slime-cells#9]
(this is somewhat related to https://github.com/Klafyvel/vim-slime-cells/issues/8)

quarto qmd files use cell delimiters that look something like:

```
```python

or

```{python}
```

I'm trying to use a delimiter regex to catch both; I currently have the following but doesnt seem to be working:
`vim.g.slime_cell_delimiter = "^```{?%a+}?$"`

any thoughts on why that pattern doesnt seem to be matching either? does the plugin use standard regex or lua match patterns?

**Comment by Klafyvel** [comment]
Hi! the plugin is pure vimscript. The regexp you are looking for is `^```{\?\a\+}\?$` .

**Comment by thesimonho** [comment]
perfect, thanks!
